time_dis/main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('daily/task/success', SuccessTaskView.as_view(), name='task_success'),
    path('daily/subtask/success', SuccessSubtaskView.as_view(), name='subtask_success'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('my_progress/', TasksProgressView.as_view(), name='my_progress'),
]

time_dis/tasks_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('add_task/', add_task, name='add_task'),
    path('add_task/<int:task_pk>/subtask/', login_required(SubtaskCreateView.as_view()), name='add_subtask'),
    path('my_tasks/', TaskList.as_view(), name='my_tasks'),
    path('delete_task/<str:slug>', delete_task, name='delete_task'),
    path('task/<str:slug>', TaskDetail.as_view(), name='task'),
    path('update_task/<str:slug>', update_task, name='update_task'),
    path('my_tasks/search/', TaskSearch.as_view(), name='task_search'),
    path('my_tasks/category/<str:category>/', tasks_by_category, name='tasks_by_category'),
    path('my_tasks/priority/<str:priority>/', tasks_by_priority, name='tasks_by_priority'),
    path('task/<str:task_slug>/subtask/create/', login_required(NewSubtaskView.as_view()), name='new_subtask'),
    path(
        'task/<str:task_slug>/subtask/update/<int:pk>/',
        login_required(SubtaskUpdateView.as_view()),
        name='update_subtask'
    ),
    path(
        'task/<str:task_slug>/subtask/delete/<int:pk>/',
        login_required(SubtaskDeleteView.as_view()),
        name='delete_subtask'
    )
]

time_dis/time_dis/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls')),
    path('', include('main.urls')),
    path('tasks/', include('tasks_app.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

time_dis/tasks_app/models.py
from django_unique_slugify import unique_slugify
from unidecode import unidecode
from django.db import models
from auth_app.models import Users
from django.urls import reverse
from django.utils.text import slugify


class Categories(models.Model):
    title = models.CharField('Название', max_length=250)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']

    def __str__(self):
        return self.title


class Priority(models.Model):
    title = models.CharField('Название', max_length=250, default='Важно-срочно')
    tag = models.CharField('Тег', max_length=100, default='danger')

    class Meta:
        verbose_name = 'Приоритет'
        verbose_name_plural = 'Приоритеты'
        ordering = ['title']

    def __str__(self):
        return self.title


class Tasks(models.Model):
    REMIND_TYPE = [('Never', 'Никогда'), ('OneTime', 'Один раз'), ('EveryDay', 'Каждый день')]

    slug = models.SlugField(max_length=250, null=True, allow_unicode=True)
    title = models.CharField('Название', max_length=250)
    comment = models.TextField('Подробности', blank=True)
    category = models.ForeignKey(Categories, on_delete=models.PROTECT, related_name='tasks', verbose_name='Категория')
    priority = models.ForeignKey(Priority, on_delete=models.PROTECT, related_name='tasks', verbose_name='Приоритет')
    remind_type = models.CharField(verbose_name='Напоминать', choices=REMIND_TYPE, max_length=20, default='OneTime')
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='tasks')
    progress = models.BooleanField('Прогресс', default=0)
    deadline = models.DateTimeField('Срок выполнения', blank=True, null=True)
    created_on = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_on = models.DateTimeField('Дата изменения', auto_now=True)
    failed = models.BooleanField('Просрочено', default=0)

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = ['-created_on']

    def save(self, *args, **kwargs):
        if not self.pk:
            unique_slugify(self, slugify(unidecode(self.title)))
        super(Tasks, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('task', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.user}: {self.title}"


class Subtasks(models.Model):
    task = models.ForeignKey(
        verbose_name='Задача',
        to=Tasks,
        on_delete=models.CASCADE,
        related_name='subtasks'
    )
    title = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    comment = models.TextField(
        verbose_name='Подробности',
        blank=True
    )
    progress = models.BooleanField(
        'Прогресс',
        default=0
    )

    class Meta:
        verbose_name = 'Подзадача'
        verbose_name_plural = 'Подзадачи'
        ordering = ['title']

    def __str__(self):
        return self.title

time_dis/tasks_app/forms.py
from django import forms
from .models import Tasks, Subtasks


class TasksForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['title', 'comment', 'category', 'priority', 'deadline', 'remind_type']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название задачи...'}),
            'comment': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Выберете категорию задачи...'}),
            'priority': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Выберете приоритет для задачи..'}),
            'deadline': forms.DateInput(attrs={'class': 'form-control', 'type': 'datetime-local',
                                               'placeholder': 'Установите срок выполнения...'}),
            'remind_type': forms.Select(attrs={'class': 'form-control'})
        }


class SubtasksForm(forms.ModelForm):
    class Meta:
        model = Subtasks
        fields = ['title', 'comment']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название подзадачи...'}),
            'comment': forms.TextInput(attrs={'class': 'form-control'})
        }

time_dis/tasks_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.timezone import now
from django.views.generic import ListView, DetailView, CreateView, UpdateView, RedirectView
from .models import Tasks, Subtasks
from main.models import TasksProgress
from .forms import TasksForm, SubtasksForm
from django.db.models import Q, F
from django.core.paginator import Paginator


def chek_failed_tasks():
    tasks = Tasks.objects.filter(deadline__date__lt=now().date()).all()
    updated_progress = list()
    for task in tasks:
        if task.progress == 1:
            task.delete()
        elif task.failed == 1:
            continue
        else:
            task.failed = 1
            task.save()
            for progress_range, _ in TasksProgress.PROGRESS_RANGE:
                t_progress, _ = TasksProgress.objects.get_or_create(
                    user=task.user,
                    category_name=task.category.title,
                    progress_range=progress_range
                )
                t_progress.task_failed = F('task_failed') + 1
                updated_progress.append(t_progress)
    if updated_progress:
        TasksProgress.objects.bulk_update(updated_progress, ['task_failed'])
    print('Проверка устаревших задач прошла успешно')


class TaskList(LoginRequiredMixin, ListView):
    model = Tasks
    template_name = 'tasks_app/task_list.html'
    context_object_name = 'tasks'
    extra_context = {'title': 'задачи', 'url_name': reverse_lazy('my_tasks')}
    paginate_by = 10

    def filter_by(self, order):
        return Tasks.objects.filter(user=self.request.user).select_related('category', 'priority')\
            .prefetch_related('subtasks').order_by(order).all()

    def get_queryset(self):
        if self.request.GET.get('filter_by'):
            return self.filter_by(self.request.GET.get('filter_by'))
        return Tasks.objects.filter(user=self.request.user).select_related('category', 'priority')\
            .prefetch_related('subtasks').all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskList, self).get_context_data(**kwargs)
        if self.request.GET.get('filter_by'):
            context['filter_by'] = f"&filter_by={self.request.GET.get('filter_by')}"

        striped_by = self.request.GET.get('striped_by')
        if striped_by:
            context['striped_by_url'] = f"&striped_by={striped_by}"
        context['striped_by'] = striped_by
        return context


class TaskSearch(LoginRequiredMixin, ListView):
    template_name = 'tasks_app/task_list_search.html'
    paginate_by = 10
    context_object_name = 'tasks'
    extra_context = {'url_name': reverse_lazy('task_search')}
    # Проблемы с поиском кириллицы можно решить при переходе на PostgreSQL

    def filter_by(self, order):
        return Tasks.objects.filter(Q(user=self.request.user) &
                                    Q(title__icontains=self.request.GET.get('search_word')))\
            .select_related('category', 'priority').order_by(order).all()

    def get_queryset(self):
        if self.request.GET.get('filter_by'):
            return self.filter_by(self.request.GET.get('filter_by'))
        return self.request.user.tasks.filter(title__icontains=self.request.GET.get('search_word'))\
            .select_related('category', 'priority').all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskSearch, self).get_context_data(**kwargs)
        context['search_word'] = f"search_word={self.request.GET.get('search_word')}"
        context['title'] = self.request.GET.get('search_word')
        if self.request.GET.get('filter_by'):
            context['filter_by'] = f"&filter_by={self.request.GET.get('filter_by')}"

        striped_by = self.request.GET.get('striped_by')
        if striped_by:
            context['striped_by_url'] = f"&striped_by={striped_by}"
        context['striped_by'] = striped_by
        return context


@login_required
def tasks_by_category(request, category):
    def filter_by(order):
        return request.user.tasks.filter(category__title=category).select_related('category', 'priority')\
            .order_by(order).all()
    data = {'title': f'задачи по категории: {category}', 'url_name': reverse_lazy('tasks_by_category', args=[category])}
    if request.GET.get('filter_by'):
        tasks = filter_by(request.GET.get('filter_by'))
        data['filter_by'] = f"&filter_by={request.GET.get('filter_by')}"
    else:
        tasks = request.user.tasks.filter(category__title=category).select_related('category', 'priority').all()
    page_obj = Paginator(tasks, 10).get_page(request.GET.get('page', 1))
    data['tasks'] = page_obj
    data['page_obj'] = page_obj

    striped_by = request.GET.get('striped_by')
    if striped_by:
        data['striped_by_url'] = f"&striped_by={striped_by}"
    data['striped_by'] = striped_by
    return render(request, 'tasks_app/task_list.html', data)


@login_required
def tasks_by_priority(request, priority):
    def filter_by(order):
        return request.user.tasks.filter(priority__title=priority).select_related('category', 'priority')\
            .order_by(order).all()
    data = {'title': f'задачи по приоритету: {priority}',
            'url_name': reverse_lazy('tasks_by_priority', args=[priority])}
    if request.GET.get('filter_by'):
        tasks = filter_by(request.GET.get('filter_by'))
        data['filter_by'] = f"&filter_by={request.GET.get('filter_by')}"
    else:
        tasks = request.user.tasks.filter(priority__title=priority).select_related('category', 'priority').all()
    page_obj = Paginator(tasks, 10).get_page(request.GET.get('page', 1))
    data['page_obj'] = page_obj
    data['tasks'] = page_obj

    striped_by = request.GET.get('striped_by')
    if striped_by:
        data['striped_by_url'] = f"&striped_by={striped_by}"
    data['striped_by'] = striped_by
    return render(request, 'tasks_app/task_list.html', data)


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Tasks
    template_name = 'tasks_app/task.html'
    context_object_name = 'task'

    def get_queryset(self):
        return Tasks.objects.prefetch_related('subtasks').select_related('category', 'priority').filter(
            user=self.request.user
        )

    def get_context_data(self, **kwargs):
        context = super(TaskDetail, self).get_context_data(**kwargs)
        context['subtasks'] = self.object.subtasks.all()
        return context


@login_required
def add_task(request):
    if request.method == 'POST':
        form = TasksForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            if 'add_subtask' in request.POST:
                return redirect('add_subtask', task_pk=task.pk)
            return redirect('my_tasks')
    else:
        form = TasksForm()
    return render(request, 'tasks_app/add_task.html', {'form': form})


@login_required
def update_task(request, slug):
    task = request.user.tasks.get(slug=slug)
    if request.method == 'POST':
        form = TasksForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect(reverse('task', kwargs={'slug': slug}))
    else:
        form = TasksForm(instance=task)
    return render(request, 'tasks_app/update_task.html', {'form': form})


@login_required
def delete_task(request, slug):
    task = request.user.tasks.get(slug=slug)
    task.delete()
    if request.META['HTTP_REFERER'] == f"http://{request.META['HTTP_HOST']}/":
        return redirect('main')
    return redirect('my_tasks')


class SubtaskCreateView(AccessMixin, CreateView):
    model = Subtasks
    template_name = 'tasks_app/subtask_create.html'
    form_class = SubtasksForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        if 'create_finish' in self.request.POST:
            return reverse('my_tasks')
        return reverse('add_subtask', kwargs={'task_pk': self.kwargs.get('task_pk')})

    def form_valid(self, form):
        subtask = form.save(commit=False)
        task = Tasks.objects.get(pk=self.kwargs.get('task_pk'))
        subtask.task = task
        subtask.save()
        return super(SubtaskCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(SubtaskCreateView, self).get_context_data(**kwargs)
        context['task_pk'] = self.kwargs.get('task_pk')
        return context


class NewSubtaskView(AccessMixin, CreateView):
    model = Subtasks
    template_name = 'tasks_app/new_subtask.html'
    form_class = SubtasksForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('task', kwargs={'slug': self.kwargs.get('task_slug')})

    def form_valid(self, form):
        subtask = form.save(commit=False)
        task = Tasks.objects.get(slug=self.kwargs.get('task_slug'))
        subtask.task = task
        subtask.save()
        return super(NewSubtaskView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(NewSubtaskView, self).get_context_data(**kwargs)
        task = Tasks.objects.get(slug=self.kwargs.get('task_slug'))
        context['task_title'] = task.title
        return context


class SubtaskUpdateView(AccessMixin, UpdateView):
    model = Subtasks
    template_name = 'tasks_app/update_subtask.html'
    form_class = SubtasksForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('task', kwargs={'slug': self.kwargs.get('task_slug')})


class SubtaskDeleteView(AccessMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('task', kwargs={'slug': self.kwargs.get('task_slug')})

time_dis/tasks_app/templates/tasks_app/add_task.html
{% extends 'base.html' %}

{% block title %} Создание задачи {% endblock %}

{% block content %}
<div class="container" style="margin-top: 15px">
    <div class="text-center p-3">
        <h1 class="display-4">Добавление новой задачи</h1>
    </div>
    <br>
    <form method="post">
        <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <br>
        <div class="form-group">
            <input type="submit" class="btn btn-outline-info" name="add_subtask" value="Добавить подзадачу">
            <input type="submit" class="btn btn-outline-success" value="Создать задачу">
        </div>
    </form>
</div>
{% endblock %}

time_dis/tasks_app/templates/tasks_app/base_tasks_app.html
{% extends 'base.html' %}
{% load task_tags %}

{% block title %} Мои {% endblock %}

{% block content %}
<div class="container">
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <h1 class="display-6">Ваши {{ title }}:</h1>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#search" aria-controls="search" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-chevron-down"></i>
            </button>
        </div>
    </nav>
    <div class="collapse" id="search">
        {% search_task %}
        <br>
        <div class="btn-group border-top border-bottom rounded w-100">
            <div class="row">
                <div class="col border-end">
                    <h3>Фильтры:</h3>
                    {% get_filters url=url_name cur_filter=filter_by %}
                </div>
                <div class="col-lg-3">
                    <h3>Разделы:</h3>
                    {% get_categories request.user %}
                    {% get_priorities request.user %}
                </div>
            </div>
        </div>
    </div>
    {% block body %} {% endblock %}
    <div class="bg-dark mt-5">
        {% if page_obj|length > 0 %}
            <nav aria-label="PaginationBar">
                <ul class="pagination justify-content-center p-3">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}{{ filter_by }}{{ striped_by_url }}" class="page-link"><i class="bi bi-arrow-left"></i></a>
                    </li>
                    {% endif %}
                    {% for p in page_obj.paginator.page_range %}
                        {% if page_obj.number == p %}
                            <li class="page-item active" aria-current="page">
                                <a href="?page={{ p }}{{ filter_by }}{{ striped_by_url }}" class="page-link">{{ p }}</a>
                            </li>
                        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                            <li class="page-item">
                                <a href="?page={{ p }}{{ filter_by }}{{ striped_by_url }}" class="page-link">{{ p }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}{{ filter_by }}{{ striped_by_url }}" class="page-link"><i class="bi bi-arrow-right"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
        </div>
</div>
{% endblock %}

time_dis/tasks_app/templates/tasks_app/category_list.html
<button type="button" class="btn btn-outline-info dropdown-toggle dropdown-toggle-split mb-2" data-bs-toggle="dropdown" aria-expanded="false">Задачи по категориям</button>
<ul class="dropdown-menu dropdown-menu-right">
    <li>
        <a class="dropdown-item" href="{% url 'my_tasks' %}">
            Все&nbsp<span class="badge bg-danger rounded-pill">{{ all_cnt }}</span>
        </a>
    </li>
    <div class="dropdown-divider"></div>
    {% for category in categories %}
        <li>
            <a class="dropdown-item" href="{% url 'tasks_by_category' category.title %}">
            {{ category.title }}
            &nbsp<span class="badge bg-danger rounded-pill">{{ category.cnt }}</span>
            </a>
        </li>
    {% endfor %}
</ul>

time_dis/tasks_app/templates/tasks_app/striped_tasks_by_datetime.html
{% load task_tags %}

<div class="row gy-5">
    {% if not tasks_without_deadline and not tasks_list %}
    <p class="text-center display-6">У вас ещё нет задач
        <br><a class="btn btn-outline-success w-25 text-center mt-3" href="{% url 'add_task' %}">Создать задачу</a>
    </p>
    {% else %}
    {% for task in tasks_without_deadline %}
    <div class="col" align="center">
        <div class="card mb-4 h-100 bg-dark rounded border" style="width: 20rem;">
            {% if task.failed %}
            <div class="card-header border-bottom bg-secondary">
                <p class="card-text fs-3">Просрочено</p>
                <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
            </div>
            {% else %}
            <div class="card-header border-bottom bg-{{ task.priority.tag }}">
                <p class="card-text fs-3">{{ task.category }}</p>
                <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
            </div>
            {% endif %}
            <div class="card-body">
                <p class="card-text fs-3">{{ task.title|title }}</p>
                {% if task.subtasks.all.exists %}
                <p><i class="bi bi-check-square"></i> {% get_subtasks_info task.subtasks.all %}</p>
                {% endif %}
                {% if task.deadline %}
                <p class="card-text">Срок выполнения: до {{ task.deadline|date:"d.m.Y" }}</p>
                {% endif %}
            </div>
            <div class="card-footer">
                <div class="btn-group w-100">
                    <a class="btn btn-outline-info w-100" href="{{ task.get_absolute_url }}">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}


    {% if striped_by == 'datetime_stripe' %}
    {% for task_date, tasks_by_time in tasks_list.items %}
    <h3 class="bg-secondary rounded-top">Задачи за {{ task_date }}</h3>
    {% for task_time, tasks in tasks_by_time.items %}
    <h4>Задачи на следующий час: {{ task_time }}:00 <hr></h4>
    {% for task in tasks %}
    <div class="col" align="center">
        <div class="card mb-4 h-100 bg-dark rounded border" style="width: 20rem;">
            {% if task.failed %}
            <div class="card-header border-bottom bg-secondary">
                <p class="card-text fs-3">Просрочено</p>
                <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
            </div>
            {% else %}
            <div class="card-header border-bottom bg-{{ task.priority.tag }}">
                <p class="card-text fs-3">{{ task.category }}</p>
                <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
            </div>
            {% endif %}
            <div class="card-body">
                <p class="card-text fs-3">{{ task.title|title }}</p>
                {% if task.subtasks.all.exists %}
                <p><i class="bi bi-check-square"></i> {% get_subtasks_info task.subtasks.all %}</p>
                {% endif %}
                {% if task.deadline %}
                <p class="card-text">Срок выполнения: до {{ task.deadline|date:"d.m.Y H:i" }}</p>
                {% endif %}
            </div>
            <div class="card-footer">
                <div class="btn-group w-100">
                    <a class="btn btn-outline-info w-100" href="{{ task.get_absolute_url }}">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endfor %}
    {% endfor %}

    {% else %}

    {% for task_date, tasks in tasks_list.items %}
    <h3 class="bg-secondary rounded-top"> Задачи за {{ task_date }}</h3>
    {% for task in tasks %}
    <div class="col" align="center">
        <div class="card mb-4 h-100 bg-dark rounded border" style="width: 20rem;">
            {% if task.failed %}
            <div class="card-header border-bottom bg-secondary">
                <p class="card-text fs-3">Просрочено</p>
                <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
            </div>
            {% else %}
            <div class="card-header border-bottom bg-{{ task.priority.tag }}">
                <p class="card-text fs-3">{{ task.category }}</p>
                <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
            </div>
            {% endif %}
            <div class="card-body">
                <p class="card-text fs-3">{{ task.title|title }}</p>
                {% if task.subtasks.all.exists %}
                <p><i class="bi bi-check-square"></i> {% get_subtasks_info task.subtasks.all %}</p>
                {% endif %}
                {% if task.deadline %}
                <p class="card-text">Срок выполнения: до {{ task.deadline|date:"d.m.Y H:i" }}</p>
                {% endif %}
            </div>
            <div class="card-footer">
                <div class="btn-group w-100">
                    <a class="btn btn-outline-info w-100" href="{{ task.get_absolute_url }}">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    {% endif %}
</div>

time_dis/tasks_app/templates/tasks_app/task_list.html
{% extends 'tasks_app/base_tasks_app.html' %}

{% load task_tags %}

{% block title %} {{ block.super }} {{ title }} {% endblock %}

{% block body %}
<ul class="nav nav-tabs mt-3">
    <li class="nav-item">
        {% if striped_by == 'date_stripe' %}
        <a class="nav-link active" aria-current="page" href="{% url 'my_tasks' %}">
            Разделение по дате
        </a>
        {% else %}
        <a class="nav-link text-white" aria-current="page" href="?striped_by=date_stripe">
            Разделение по дате
        </a>
        {% endif %}
    </li>
    <li class="nav-item">
        {% if striped_by == 'datetime_stripe' %}
        <a class="nav-link active " href="{% url 'my_tasks' %}">
            Разделение по дате и времени
        </a>
        {% else %}
        <a class="nav-link text-white" href="?striped_by=datetime_stripe">
            Разделение по дате и времени
        </a>
        {% endif %}
    </li>
</ul>
<div class="album py-5 bg-dark rounded">
    <div class="container">
        {% if striped_by %}
        {% get_striped_tasks_by_datetime tasks_list=tasks stripe_type=striped_by %}
        {% else %}
        <div class="row gy-5">
            {% for task in tasks %}
            <div class="col" align="center">
                <div class="card mb-4 h-100 bg-dark rounded border" style="width: 20rem;">
                    {% if task.failed %}
                    <div class="card-header border-bottom bg-secondary">
                        <p class="card-text fs-3">Просрочено</p>
                        <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
                    </div>
                    {% else %}
                    <div class="card-header border-bottom bg-{{ task.priority.tag }}">
                        <p class="card-text fs-3">{{ task.category }}</p>
                        <a href="{% url 'delete_task' task.slug %}" class="btn btn-close btn-close-white text-right" style="position: absolute; right: 5px; top: 5px;"></a>
                    </div>
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text fs-3">{{ task.title|title }}</p>
                        {% if task.subtasks.all.exists %}
                        <p><i class="bi bi-check-square"></i> {% get_subtasks_info task.subtasks.all %}</p>
                        {% endif %}
                        {% if task.deadline %}
                        <p class="card-text">Срок выполнения: до {{ task.deadline|date:"d.m.Y" }}</p>
                        {% endif %}
                    </div>
                    <div class="card-footer">
                        <div class="btn-group w-100">
                            <a class="btn btn-outline-info w-100" href="{{ task.get_absolute_url }}">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-center display-6">У вас ещё нет задач
                <br><a class="btn btn-outline-success w-25 text-center mt-3" href="{% url 'add_task' %}">Создать задачу</a>
            </p>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}